db:
  user: root
  password: P2_190vIP.X2
  host: 192.168.180.122
  port: 3306
  db_name: asppay_real_2
  max_idle_conns: 10
  max_open_conns: 100
redis:
  host: 192.168.180.122
  port: 6379
  auth: Q1._92oP
  db: 2
log:
  storage_location: ./logs/
  max_age: 24
  max_backups: 5
  max_size: 5
  log_level: debug
server:
  name: asp-payment-api-server
  port: 5151
  env: Test
