db:
  user: rootsunnypay
  password: q2kAR9F,I
  host: paycluster.cluster-cllzldcgerxe.ap-east-1.rds.amazonaws.com
  port: 3306
  db_name: sunnypay
  max_idle_conns: 10
  max_open_conns: 100
redis:
  host: 172.31.44.193
  port: 6379
  auth: Ks0S_1.O0
  db: 2
log:
  storage_location: ./logs/
  max_age: 24
  max_backups: 5
  max_size: 100
  log_level: debug
server:
  name: sunny-payment-api-server
  port: 5152
  env: Production # Test Dev Production
  admin_secret: iXNtGXq3HyYAnAPXjQhi2UdjFHy0uMQc
urls:
  wap_pay_checkout_pre_url: "https://apiprod.sunnypay.net/pay/checkout"   #wappay 收银台支付url前缀
  wap_pay_checkout_qrcode_url: "https://apiprod.sunnypay.net/pay/qrcode"
  zpay_payout_notify_url: "https://apiprod.sunnypay.net/callback/zpay/payout"
  zpay_h5_notify_url: "https://apiprod.sunnypay.net/callback/zpay/order"
  seveneight_h5_notify_url: "https://apiprod.sunnypay.net/callback/seveneight/order"
  amarquickpay_wappay_notify_url: "https://apiprod.sunnypay.net/callback/amarquickpay/order"
  seveneight_payout_notify_url: "https://apiprod.sunnypay.net/callback/seveneight/payout"
  seveneight_order_return_url: "https://apiprod.sunnypay.net/notify/order/return_success"
  fynzonpay_wappay_notify_url: "https://apiprod.sunnypay.net/callback/fynzonpay/order"
  fynzonpay_wappay_error_url: "https://apiprod.sunnypay.net/notify/order/return_error"
  fynzonpay_beneficiary_notify_url: "https://apiprod.sunnypay.net/callback/fynzonpay/beneficiary"
  fynzonpay_payout_notify_url: "https://apiprod.sunnypay.net/callback/fynzonpay/payout"
  fynzonpay_payout_error_url: "https://apiprod.sunnypay.net/notify/order/return_error"
  fynzonpay_order_return_url: "https://apiprod.sunnypay.net/notify/order/return_success"
jobConfig:
  # 查询到前 n 天的日志
  query_before_day: 10